/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ImageSocialMedia } from "./ImageSocialMedia";
export * as factories from "./factories";
export { ImageSocialMedia__factory } from "./factories/ImageSocialMedia__factory";
